platform :ios, '8.0'
use_frameworks!

target 'SGDTestLogDemo' do

end

target 'SGDTestLogDemoTests' do
    pod 'SGDTestLog', :path => '..'
    pod 'Quick'
    pod 'Nimble'
end

post_install do | installer |
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
        end
    end
end
